# Generated by Django 5.0.4 on 2024-05-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_favorit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='daftar_favorit',
            new_name='data_daftar_favorit',
        ),
    ]
