# Generated by Django 4.2.7 on 2024-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_favorit', '0002_rename_daftar_favorit_data_daftar_favorit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarFavorit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
    ]
